#!/usr/bin/env python
# -*- python -*-
from __future__ import print_function
import os, sys, re, time, datetime, argparse
from LMODdb import LMODdb

class CmdLineOptions(object):
  """ Command line Options class """

  def __init__(self):
    """ Empty Ctor """
    pass
  
  def execute(self):
    """ Specify command line arguments and parse the command line"""
    parser = argparse.ArgumentParser()
    parser.add_argument("--dbname",      dest='dbname',  action="store",      default = "lmod",    help="lmod db name")
    parser.add_argument("--syshost",     dest='syshost', action="store",      default = "unknown", help="system host name")
    parser.add_argument("--mfile",       dest='mfile',   action="store",      default = "unknown", help="file containing module filenames")

    args = parser.parse_args()
    return args

def dbConfigFn(dbname):
  """
  Build config file name from dbname.
  @param dbname: db name
  """
  return dbname + "_db.conf"

def main():
  args     = CmdLineOptions().execute()
  configFn = dbConfigFn(args.dbname)
  lmod     = LMODdb(configFn)
  
  



if ( __name__ == '__main__'): main()
