#!/bin/sh
# -*- python -*-

################################################################################
# This file is python 2/3 bilingual. 
# The line """:" starts a comment in python and is a no-op in shell.
""":"
# Shell code to find and run a suitable python interpreter.
for cmd in python3 python python2; do
   command -v > /dev/null $cmd && exec $cmd $0 "$@"
done

echo "Error: Could not find a valid python interpreter --> exiting!" >&2
exit 2
":""" # this line ends the python comment and is a no-op in shell.
################################################################################

from __future__ import print_function
import os, sys, re, time, argparse, json, operator
from LMODdb import LMODdb

class CmdLineOptions(object):
  """ Command line Options class """

  def __init__(self):
    """ Empty Ctor """
    pass
  
  def execute(self):
    """ Specify command line arguments and parse the command line"""
    parser = argparse.ArgumentParser()
    parser.add_argument("-D",            dest='debug',    action="store_true",                           help="Debug Flag")
    parser.add_argument("--confFn",      dest='confFn',   action="store",      default="lmodV2_db.conf", help="Name of the database")
    parser.add_argument("--ignoreFn",    dest='ignoreFn', action="store",                                help="List of module patterns to ignore")
    parser.add_argument("dataFn",                                                                        help="Syslog/Json file name")
    args = parser.parse_args()
    return args


class Ignore(object):
  def __init__(self, ignoreFn):
    if (not ignoreFn):
      self.__ignoreA = []
      return

    ignoreA = []
    with open(ignoreFn, 'r') as file:
    # Read each line in the file
      for line in file:
        ignoreA.append(re.compile(line.strip()))
    self.__ignoreA = ignoreA

  def ignore(self, module):
    result = False
    for rex in self.__ignoreA:
      match = rex.match(module)
      if (match):
        result = True
        break

    return result


def syshost(name):
  hostA = name.split('.')
  idx   = 1
  if (len(hostA) < 2):
    idx = 0
  return hostA[idx]

def main():

  args = CmdLineOptions().execute()

  lmod = LMODdb(args.confFn)
  
  
  baseNm, extension = os.path.splitext(args.dataFn)

  ignore = Ignore(args.ignoreFn)

  f = open(args.dataFn,"r")

  icount = 0
  modulePatt = re.compile(r'.*ModuleUsageTracking[^ ]* *')
  
  usageT = {}
  for count, line in enumerate(f):
    line  = line.rstrip("\n")
    if (extension == ".json"):
      dataT = json.loads(line)
    else:
      rest  = modulePatt.sub('',line)
      dataT = dict(re.findall(r'(\S+)=(".*?"|\S+)', rest))
      host  = dataT.get('host')
      dataT['syshost'] = syshost(host)
      dataT['date']    = dataT['time']
      dataT.pop('time',None)
      dataT.pop('host',None)
  
    if (dataT.get('syshost') == None):
      continue
      print(line)

    # check if module is in the ignore list
    # if so skip it.
    module = dataT.get('module')
    if (ignore.ignore(module)):
      continue

    key = dataT['user'] + ' ' + dataT['syshost'] + ' ' + dataT['module'] + ' ' + dataT['path']
    if (not key in usageT):
      usageT[key] = { 'user'    : dataT['user'],
                      'syshost' : dataT['syshost'],
                      'module'  : dataT['module'],
                      'path'    : dataT['path'],
                      'date'    : dataT['date'],
                      }
    
  blkSz = 1000
  dataA = []
  icount = 0
  for value in usageT.values():
    if (icount < blkSz):
      dataA.append(value.copy())
    else:
      lmod.data_to_db(args.debug, dataA)
      dataA.clear()
      dataA.append(value.copy())
      icount = 0
    icount += 1
    
  dataA.sort(key=operator.itemgetter('date'))

  lmod.data_to_db(args.debug, dataA)
  f.close()


if ( __name__ == '__main__'): main()
