#!/bin/bash
# -*- shell-script -*-

projectDir=$1
epoch=$(lua -e 'print(os.time())')
dateStr=$(date -R)

cmd=$projectDir/proj_mgmt/build_hide_cmd
echo "--" '>' " CurrentTime: $dateStr"

$cmd  $epoch ACME/1.0 after  -120 ""
$cmd  $epoch ACME/2.0 after   120 ""
$cmd  $epoch ACME/3.0 before -120 ""
$cmd  $epoch ACME/4.0 before  120 ""

$cmd  $epoch B/1.0    after  -120 "kind=\"hard\""
$cmd  $epoch B/2.0    after   120 "kind=\"hard\""


