Ways to explain settarg

* What is settarg?
** Connected to module loaded
** Set env. var. automatically.

* Beginning Level
** just have the module command automatically call settarg
with no prompt command, no changing the title bar, no changing via
Hermes.db or similar

** Note: Could, Should settarg functionality be integrated directly into Lmod?
How would one control the output?  Would there be a settarg module? or
would it always be on?

* Advanced Level
** Simply add the settings in the setup files for lmod.
This will probably have to be a configure option.  Which I don't like
but there is no good way to do this.

* How would one use it?
** The main benefit is to build systems:
One gets a single environment variable "TARG" which encapsulates the
state of the loaded modules, plus the machine architecture
(x86_64_06_1a) and optionally a BUILD_SCENARIO (opt, dbg, mdbg, etc)
Plus settarg provides host of environment variables to check various
states.

You get

   TARG_COMPILER
   TARG_COMPILER_FAMILY
   TARG_MPI
   TARG_MPI_FAMILY
   TARG_BUILD_SCENARIO

This supports a host of tests that can be part of a Makefile or other
build systems.

Also included are separate executables available at the same time.
This makes comparing and contrasting easy.

* O.K.  I have drunk the Kool-aid and I love this stuff but how am I going to use this at home? At Work?

Well it is easy to install Lmod on personal systems.  But you'd also
have to install the module files as well.   Easy enough but ...

It is also possible that one sets these variables by hand or in a
.bashrc or similar file on a system where you only build it one way.

Complain to your administrator that they should be using Lmod!!!.


* There is a great deal of useful info in the module table.
This is one way to make his information available to codes
